apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hello-app
  labels:
    app: node-hello-app
spec:
  selector:
    matchLabels:
      app: node-hello-app
  template:
    metadata:
      labels:
        app: node-hello-app
    spec:
      containers:
        - name: mynode-app
          image: navadeepraja/node-hello-app:master
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: node-hello-app-svc
spec:
  selector:
    app: node-hello-app
  ports:
    - protocol: "TCP"
      name: http
      port: 80
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-api-ingress
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: api.vapourgames.com
      http:
        paths:
          - path: /node-example(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: node-hello-app-svc
                port:
                  number: 80
  ingressClassName: nginx

---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
spec:
  controller: k8s.io/ingress-nginx
